### ISSUE TITLE
Esc

### ISSUE THREAD

**Issue by z3t0** [deathcap/voxel-inventory-dialog#2]
Hitting escape does not take you out of the inventory

**Comment by z3t0** [comment]
You must click out

**Comment by deathcap** [comment]
Unfortunately I can't use escape for this purpose because the browser reserves this key for exiting pointer lock. 

The escape key press event can be handled, used to close modal dialogs, but then you expect to return back to the game except since pointer lock is released, you need to click in the browser to re-acquire it. For this reason there are two ways to exit voxel-modal dialogs: either click outside of the dialog, or press the backquote key ("`", usually next to Esc - basically any key but Esc will work). More details in:

https://github.com/deathcap/voxel-modal/issues/1

**Comment by z3t0** [comment]
@deathcap Okay that clears things up, too bad ESC does not work.
